## Json 6902 Patch

patches:
  - target:
      kind: Deployment
      name: api-deployment
    
    patch: | -
      - op: replace 
        path: /metadata/name
        value: web-deployment
    
    patch: | -
      - op: replace
        path: /spec/replicas
        value: 5

## In kustomize there are two ways to define patch Json 6902 or Strategic Merge Patch 


## Strategic merge patch (regular kubernetes config)

patches:
  - patch: | - 
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-deployment
    spec:
      replicas: 5